name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create config file in root (not /dist)
      - name: Create Supabase config
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "export const SUPABASE_CONFIG = {
            url: '$SUPABASE_URL',
            key: '$SUPABASE_KEY'
          };" > config.js

      # 3. Deploy entire repo (or specific folder)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploys root folder (or use ./dist if you have one)
